# -*- coding: utf-8 -*-
__author__ = 'Evolutiva'

db.define_table('persona_draft',
    Field('current_record','integer',required=True),
    Field('status','string', required=True, requires=IS_IN_SET('draft','locked'), default='draft'),
    Field('ICN','string',label=T('rut'), required=False),
    Field('firstName', 'string', readable=True, writable=True, label=T('Nombres')),
    Field('firstLastName', 'string', label=T('Apellido 1')),
    Field('otherLastName', 'string', readable=True, writable=True, label=T('Apellido 2')),
    Field('alias', 'string', readable=True, writable=True, label=T('Nombre Corto')),
    Field('birth', 'string', label='Fecha de Nacimiento', required=False),
    Field('countryofResidence',db.country, label='País de Residencia',requires=IS_IN_DB(db, 'country.id', 'country.name')),
    Field('Mainsector','list:reference sector', label=T('Main Sector'), requires = IS_IN_DB(db,'sector.id','db.sector.name',multiple=True)),
    Field('depiction','upload', label=T('Foto'), required=False),
    Field('shortBio','text', label=T('Reseña')),
    Field('longBio','text', requires=IS_LENGTH(65536), label=T('Perfil largo')),
    Field('documentSource','list:reference document',required=False,
          requires=IS_IN_DB(requiere,'document.id','%(name)s',multiple=True),
          label=T('Fuentes')),
    Field('documentCloud','list:reference documentCloud',required=False,
          requires=IS_IN_DB(db,'documentCloud.id','%(title)s',multiple=True),
          label=T('Fuentes Document Cloud')),
    Field('isDead','boolean', label=T('Ha Fallecido')),
    Field('web','string', label=T('Web')),
    Field('twitterNick','string', label=T('Twitter')),
    Field('facebookNick','string', label=T('Facebook')),
    Field('linkedinNick','string', label=T('Linkedin')),
    auth.signature,
)
